apiVersion: v1
kind: ServiceAccount
metadata:
  name: chromecast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chromecast
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chromecast
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chromecast
subjects:
  - kind: ServiceAccount
    name: chromecast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromecast
  template:
    metadata:
      name: chromecast
      labels:
        app: chromecast
        version: v1
    spec:
      containers:
        - name: chromecast
          image: REG/IMAGE:TAG
          resources:
            requests:
              memory: "3.6Gi"
              cpu: "450m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "v1"
      serviceAccountName: chromecast
---
apiVersion: v1
kind: Service
metadata:
  name: chromecast
  labels:
    app: chromecast
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
  selector:
    app: chromecast
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: chromecast-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chromecast
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
